### PR TITLE
fix 'No such file or directory' error on cygwin

### LINKED ISSUE #18: cygwin broken on windows 7 64-bit
```
$ nova
(OSError('No such file or directory',), {})
Traceback (most recent call last):
  File "/home/mfurlong/openstack/bin/nova", line 7, in <module>
    from novaclient.shell import main
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/novaclient/__init__.py", line 17, in <module>
    from novaclient import api_versions
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/novaclient/api_versions.py", line 25, in <module>
    from novaclient import utils
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/novaclient/utils.py", line 22, in <module>
    from oslo_serialization import jsonutils
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/oslo_serialization/jsonutils.py", line 42, in <module>
    from oslo_utils import timeutils
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/oslo_utils/timeutils.py", line 27, in <module>
    from monotonic import monotonic as now  # noqa
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/monotonic.py", line 169, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

### PR DESCRIPTION
**Pull request by furlongm**
closes #18

Pretty much the same as https://github.com/atdt/monotonic/pull/8

### CODE REVIEW

**Comment by dan-richards** [comment]
The `LoadLibrary` call was previously used but was [removed](https://github.com/atdt/monotonic/commit/624fa6e062a5b845424edebed4573ab3cd8a67b6#diff-5eedd9ea882bd3986640f0922643411cL101) in 624fa6e  :persevere:.

I can confirm that this fixes the error for me on Cygwin on Windows 7 x64.

**Comment by alexoughton** [comment]
I just found exactly the same thing, and found the same fix as well.

**Comment by tknerr** [comment]
Hitting the same issue today, monotonic is currently broken in Cygwin. This PR fixes it.

**Comment by tknerr** [comment]
@atdt any chance to get that fix out as a 1.2 release? Otherwise considering to install from a fork, or manually patching (eeek!) in the meantime...

**Comment by tknerr** [comment]
@atdt btw just noticed that the `1.1` tag is pushed, but the related commit does not show up in `master` yet. Probably needs an additional `git push` in addition to `git push --tags`?

**Comment by atdt** [comment]
I am sorry it took me a while to respond; I've been on family medical leave. I verified the fix, merged it, and cut a 1.2 release, which is now pushed to PyPI. @tknerr, I also pushed the commit associated with the 1.1 tag -- your assumption was correct. Thank you all very much.

**Comment by tknerr** [comment]
@atdt hope you are doing well, and big thanks for the super quick response! :+1: :+1: :+1:

**Pull request merged**
